---

- name: Update mainline kernel
  hosts: testservers
  become: True
  tasks:
    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: 'ppa:cappelikan/ppa'
    - name: Install mainline
      ansible.builtin.package: name=mainline update_cache=yes
    - name: Update kernel
      ansible.builtin.shell: mainline install-latest
    - name: Reboot machine
      ansible.builtin.reboot:
        reboot_timeout: 60

...
